package ica

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"strconv"
	"strings"
	"time"
)

type AutoGeneratedCustomer struct {
	CustomerNumber int `json:"CustomerNumber"`
	Cards          []struct {
		Accounts []struct {
			Balance       string `json:"Balance"`
			Available     string `json:"Available"`
			AccountType   string `json:"AccountType"`
			AccountName   string `json:"AccountName"`
			AccountStatus string `json:"AccountStatus"`
		} `json:"Accounts"`
		CardTypeDescription string `json:"CardTypeDescription"`
		CardTypeCode        string `json:"CardTypeCode"`
		MaskedCardNumber    string `json:"MaskedCardNumber"`
		Selected            bool   `json:"Selected"`
	} `json:"Cards"`
}
type AutoGeneratedTransactions struct {
	TransactionSummaryByMonth []struct {
		Year                 string `json:"Year"`
		Month                string `json:"Month"`
		YearMonthAsDateTime  string `json:"YearMonthAsDateTime"`
		TransactionForAMonth []struct {
			TransactionDate  string  `json:"TransactionDate"`
			MarketingName    string  `json:"MarketingName"`
			TotalDiscount    float64 `json:"TotalDiscount"`
			TransactionValue float64 `json:"TransactionValue"`
		} `json:"TransactionForAMonth"`
	} `json:"TransactionSummaryByMonth"`
}

func parseFloat(data string) (val float64, err error) {
	data = strings.Replace(data, ",", ".", 1)
	f, err := strconv.ParseFloat(data, 64)

	return f, err
}

// ParseJSON parses json
func ParseAccount(resp *http.Response, ica *Ica) (*Ica, error) {
	defer resp.Body.Close()
	jsonBlob, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return ica, err
	}
	customer := AutoGeneratedCustomer{}
	err = json.Unmarshal(jsonBlob, &customer)
	if err != nil {
		return ica, err
	}

	available, err := parseFloat(customer.Cards[0].Accounts[0].Available)
	if err != nil {
		return ica, err
	}
	ica.Available = available
	balance, err := parseFloat(customer.Cards[0].Accounts[0].Balance)
	if err != nil {
		return ica, err
	}

	ica.Balance = balance

	return ica, nil
}

// ParseTransactions parses transactions
func ParseTransactions(resp *http.Response, ica *Ica) (*Ica, error) {
	var trans []IcaTransaction
	defer resp.Body.Close()
	jsonBlob, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return ica, err
	}
	transactions := AutoGeneratedTransactions{}
	err = json.Unmarshal(jsonBlob, &transactions)
	if err != nil {
		return ica, err
	}

	for _, m := range transactions.TransactionSummaryByMonth {
		for _, tr := range m.TransactionForAMonth {
			t := IcaTransaction{}
			date, _ := time.Parse("20060102", tr.TransactionDate)
			t.Date = date
			t.Location = tr.MarketingName
			t.Discount = tr.TotalDiscount
			t.Amount = tr.TransactionValue
			trans = append(trans, t)
		}
	}
	ica.Transactions = trans

	return ica, nil
}
